language: node_js
cache:
  directories:
    - "~/.npm"
notifications:
  email: false
node_js:
  - '14'
  - '12'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run deploy-docs"; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: GGrW4HifJci10SPI6n8m9wqfUIxN5pI9ReHOxfSr8F9EBr1VxSUkLc9aZL1AT3PP/vJmnMl7FhNhAcGNlv6Xu6u2PdX2tOm84SpUTv8ZIOdGtp1Z4lJw/AQFF/M/PMQJIeKxwCjwEMCwRrdJdTZrreqXl1ApcPF/S7fxhaeJx7aT7jtiRrGu1FPCUERVgT9dl5TXowRk11pLaB5kpASFlTUX9zUxbXKvL8iNkApq4oTi+urJUSTLXED4WzTsHB+dKmnag4HJcsFOby4xA21zjg83w71xbGaDEEWqSm2XzSQ6fWOSa+eA+lZaWIA+Dl6YjECa7nfTlAOMLpm/qIUzrYjjks09YZTgLUNVv9BpCLmXyjAqZTmR/OUSBYQmAUov7JoKbmW4ETxQovdbx4gdnudIHQxgBgBFvalupZ/S/fhorLUnHVoKw4Xnfg1jKKOVrW9qWY9KzSCFCOg/5nu71V+bLFlNJdm3QU+1YTn3ifuTblbhYaa34Y1x5Pn+keNwPH6xBL8damsfvi9yKaPXzhRAruPpGOM5R/+3x65NQsu0XjezDn8wAvTjWtx7Whuz7DfUt4qRsevT1RzS9CEm/sp1HE3m1JyPx/BBsJBrygPYjR/DM5ynPmtUlbG4odUkv53rjNaoH/4q27y8QyQ9PEx7DDz5GKjGb9CbuQHTv+I=
  - secure: hGUoq+hZGQ8/JVLz0aaakTqJhfs6eOOS/oh6ISNcavBmoVX6UjTTvkRKOHix390SXdYjaXfNRHU7H4LQnn1xDbmyo0pYjowI7XLeqacCf5ObyVjc8GGxg11Vm3XXiQTL+mU+2FKyKeahuDk0vftGG8zSOAtgzxIglsEp6OuLoILLoamz19xassom63xHKgTb4cGjmLrFBxORAvniFGNuMfHYq/RTzO1O9u+0qpx8fiClJYVrhc1oio83HAT8iKppC9dvDNp4khP3zWI4RfKpC6LhwFl0SLo9I+hXn1srdi8fXwDwLnM0n+wkydqyDrSj2tpff5AQud+YPeyn5PlNnhYPjt43NmIUnzfeEObPAxO559OHIp2zbtx2Rbewp52chqHzmHNfRYen7/rA+/mYaIxwDf1A+0ahQW+/dd0VAJuuYtF+N2yiS6+5zSvITZnDm7nji/AVgMjtZVr2+W4umd+fcjlh233GYVg6Dasww1g4XmyN9/n8LY4Qju3fovXnbdYgUaJixRr7eqeKgMqndJGEdD0JF6P4a9Y1XJCAuuQrCfoJlljYis5PQIMwavP2FYGvsnvOk7VWO7qVtCp/OI73Ker8q7XZmMFRYU+mOOHTkT9fPSHCJv3e54B1e40UM1N5GoN+QgSfHlhWrmkBInhgkSIcEYZRvn6Lb2euf6o=
